### ISSUE TITLE
[Feature request] Goto next/prev sibling with the same type

### ISSUE THREAD

**Issue by thomasmore** [drybalka/tree-climber.nvim#1]
Hi.

Problem statement:
I wanted to have a single pair of mappings to navigate to prev/next classes, methods, functions etc. for all languages I have TreeSitter parser installed. And your plugin seems to match this need almost perfectly. But right now if I use `goto_next()` on class node, I may also get to comment section or include directive (c++ language). What if `goto_next_same_type()` will be introduced? Is it possible (I don't know treesitter internals)? Also if you don't mind the idea and don't have spare time, I could try to make a PR with this feature.

**Comment by drybalka** [comment]
Thank you for the suggestion! I also noticed that I often have to jump through the comments when I actually would rather skip them. But I am not sure what would be a more useful for everyone design choice:

1.  As you suggested `goto_next_same_type()` - easy to implement and to understand, but not very useful when you scroll through code that has different node types like variable declarations, function calls, etc.
2. Alternatively `goto_next(skip_comments = true/false)` - this is still easy to understand, but harder to implement, as different parser may have different names for comments or different types of comments. Besides it won't jump over the include statements.
3. Or something like `goto_next(skip_types = {'include', 'comment', ...})` - this is easy to implement, but hard for users to understand, because they should explicitly specify the node types as they are defined in parsers. This is the most flexible choice though.

What do you think?

**Comment by thomasmore** [comment]
on second thought, I think the second option is the best. It skips the majority of false jumps, but is still understandable

**Comment by drybalka** [comment]
Hey! It took a bit longer, than I would have liked, but the recent commit should add the desired functionality. If this satisfies your suggestion (if you still remember about it), then feel free to close this issue.

**Comment by thomasmore** [comment]
Thanks for the commit! Works for me perfectly
