### ISSUE TITLE
Feat: Jump to next parent if no more children

### ISSUE THREAD

**Issue by Gazareth** [drybalka/tree-climber.nvim#3]
Thanks for the plugin, it's great!

I have noticed in other similar ones you can provide an option to go to the next parent if you try to go to the next sibling node and there are none available.

Edit: Additionally if you're trying to go to a child but the current node has no further children, automatically go to its next sibling's child.

Is this something you would consider implementing for this plugin? (If it's not already possible)

**Comment by drybalka** [comment]
I am glad you like the plugin =)

One of the features of this plugin is the ability to go back to previous node - so that jumping to next and then back to prev returns you to the same node. However, with your proposal it would be unclear where you should return to if on the first jump you go to the next parent.

Besides, virtually the same functionality is achieved by simply first invoking `goto_parent` and then `goto_next` (and similar for the second proposal). If you really want you can even hack a function that does that automatically yourself - just track the cursor position after going to the next node and if it doesn't change than invoke `goto_parent` and then `goto_next`.
